### ISSUE TITLE
Paperwork is out 

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#10]
👋 

I have sent the contract papers, please sign and send the papers, thanks! I would suggest reading the papers, the contract is on the line of SoC/WoC contracts say GSoC.

cc @anuragsarkar @Armorer96  @prondubuisi @sakshivij @sujaykumarreddy.

**Comment by sakshivij** [comment]
@tapaswenipathak I didn't receive them. Have you mailed them?

**Comment by tapaswenipathak** [comment]
I sent a docusign invite.

**Comment by sakshivij** [comment]
Didn't receive any

**Comment by sakshivij** [comment]
@tapaswenipathak

**Comment by prondubuisi** [comment]
No paperwork received @tapaswenipathak

**Comment by sujay0399** [comment]
I didn't receive anything either @tapaswenipathak
