### ISSUE TITLE
Submitting Per Day Work

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#13]
**Submit per day PR**. Every day I should see the work in whatever state it is, if you push work, you would run on delay, few projects have a hard deadline. The work is running on huge delay from coding. I am there on the Slack channel for complete time, you have my number as well for any help you need, feel free in calling me, I will work on getting any issues out of the way. Per day PR and commit are necessary. Feel free following up w/ me multiple times. 

cc @anuragsarkar @Armorer96 @prondubuisi @sakshivij @sujaykumarreddy.

**Comment by prondubuisi** [comment]
Ack

**Comment by sakshivij** [comment]
Ack

**Comment by tapaswenipathak** [comment]
Folks let’s strictly follow this, submit the work in whatever state you have at the eod.

**Comment by prondubuisi** [comment]
@tapaswenipathak  for clarity sake what are the steps to submitting logs for the day? a lot of things have been said on different platforms.
Can we have the steps together in one place please

**Comment by tapaswenipathak** [comment]
On Fri, May 31, 2019 at 1:07 PM Onyemenam Ndubuisi
<notifications@github.com> wrote:
>
> @tapaswenipathak for clarity sake what are the steps for submitting logs for the day?

Let's chat in Slack channel.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
