### ISSUE TITLE
Posting daily updates on Slack channel

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#14]
Write a daily update on the Slack channel. This would be letting me know what you are spending time per day.

cc @anuragsarkar @Armorer96 @prondubuisi @sakshivij @sujaykumarreddy.

**Comment by prondubuisi** [comment]
Ack

**Comment by sakshivij** [comment]
Ack

**Comment by anuragsarkar** [comment]
Ack.

**Comment by sujay0399** [comment]
Ack
