### ISSUE TITLE
Signing documents

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#15]
You should sign and send paper work within next few days. Comment on this ticket after you have signed and submitted.

cc @anuragsarkar @Armorer96 @prondubuisi @sakshivij @sujaykumarreddy.

**Comment by prondubuisi** [comment]
@tapaswenipathak Signed and Submitted

**Comment by sakshivij** [comment]
Signed and Submitted

**Comment by anuragsarkar** [comment]
Signed & Submitted.

**Comment by sujay0399** [comment]
@tapaswenipathak Signed and Submitted.

**Comment by mamtashukla** [comment]
@tapaswenipathak  Signed and Submitted.
