### ISSUE TITLE
Missing daily log submission can result in ending the internship contract

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#16]
Failing submitting day log for multiple days can result in ending the internship contract. More information find in the paper work you signed. Feel free in submitting empty day log, saying you had an empty day. Feel free pinging me or setting a call I am all available for the interns. If the work gets boring just let me know, I have lots and lots of interesting work.

cc @anuragsarkar @Armorer96 @prondubuisi @sakshivij @sujaykumarreddy.

**Comment by prondubuisi** [comment]
Ack

**Comment by sakshivij** [comment]
ack

**Comment by anuragsarkar** [comment]
Ack

**Comment by mamtashukla** [comment]
Ack
