### ISSUE TITLE
Communication Guidelines as an Intern

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#19]
- Keep the communication focused on work. Please no stories!
- Follow proper git commits.
- Follow proper git guidelines.
- Submit the work as per review.
- Daily submission of work.
- Ack tickets.
- Daily logs submission.
- Daily syncs.

cc @anuragsarkar @Armorer96 @prondubuisi @sakshivij @sujaykumarreddy.

**Comment by prondubuisi** [comment]
Ack

**Comment by sakshivij** [comment]
Ack

**Comment by anuragsarkar** [comment]
Ack

**Comment by sujay0399** [comment]
Ack
