### ISSUE TITLE
Clarifications regarding timeline and other questions

### ISSUE THREAD

**Issue by sujay0399** [tapaswenipathak/Interns-qna#2]
- Should I commit the timeline to [timelines](https://github.com/tapaswenipathak/Timelines) repo?
- And how should I submit a calendar?
- I see that you have you a created a skeleton of YourCFP app, but it seems that it is created on a different version of django.I'm getting many errors when I try to run it on my local machine.How should I proceed.

**Comment by tapaswenipathak** [comment]
> - Should I commit the timeline to [timelines](https://github.com/tapaswenipathak/Timelines) repo?

Yes.

> - And how should I submit a calendar?

Calendly.

> - I see that you have you a created a skeleton of YourCFP app, but it seems that it is created on a different version of django.I'm getting many errors when I try to run it on my local machine.How should I proceed.

Create a base app and open a pr. You would work on the tickets assigned. Merging is my work.
