### ISSUE TITLE
Please send proper work information

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#25]
Please don't ping w/ a line of text. Write proper information

- Completed tickets
- Planned tickets
- Functionality tickets I should be reviewing
- How many days of lag
- What should be finished in next few day

for question you need help on please write properly. 

cc @anuragsarkar @mamtashukla @sakshivij @Sujaykumar

**Comment by anuragsarkar** [comment]
**Completed these ticket:-**

- https://github.com/tapaswenipathak/TheLesserNumber/issues/12 Please review.
- https://github.com/tapaswenipathak/TheLesserNumber/issues/9 Please review.
- https://github.com/tapaswenipathak/TheLesserNumber/issues/8 Please review.
- https://github.com/tapaswenipathak/TheLesserNumber/issues/6 Please review.
- https://github.com/tapaswenipathak/TheLesserNumber/issues/5 Please review.
- https://github.com/tapaswenipathak/TheLesserNumber/issues/13 Please review.

**I am updating the docs file and clearing data from excel sheet.**

**Pending & Need will check from ND because he has also collected data for these tickets.**

- https://github.com/tapaswenipathak/TheLesserNumber/issues/14
- https://github.com/tapaswenipathak/TheLesserNumber/issues/11
- https://github.com/tapaswenipathak/TheLesserNumber/issues/10
- https://github.com/tapaswenipathak/TheLesserNumber/issues/7  

Please review and let me know if any improvements required in data. Because collecting data seems large task.

I am lagging behind by 6 days. Only 4 tickets are pending from my side. I will check with ND and will try to finish it asap.

**Comment by tapaswenipathak** [comment]
You can post like this as well, works for me.

**Comment by sakshivij** [comment]
**Completed tickets**
    
 Till 15 ( Excluding the current PR)
     
**Planned tickets** 
     
BY EOD of 
-  7 june: Till Ticket number 30
-  8 June : Till Ticket number 40
-  9 June : Till Ticket number 55

**Functionality tickets I should be reviewing**

https://github.com/tapaswenipathak/GitGIFs/pull/79
https://github.com/tapaswenipathak/GitGIFs/pull/80
https://github.com/tapaswenipathak/GitGIFs/pull/81
https://github.com/tapaswenipathak/GitGIFs/pull/82
https://github.com/tapaswenipathak/GitGIFs/pull/84

Every ticket has almost 4-5 or even more GIF creation. I am mostly creating 10-15 ( approx) GIF everyday and ticket  number are huge.
  
**How many days of lag : I am lagging by 7 days.** 
    
**What should be finished in next few day**
     I aim finishing all GIF by 9 June ( excluding tickets I might need help with).

**What help do I need?**
    https://github.com/tapaswenipathak/GitGIFs/pull/78
    https://github.com/tapaswenipathak/GitGIFs/pull/77
    https://github.com/tapaswenipathak/GitGIFs/pull/76
   https://github.com/tapaswenipathak/GitGIFs/issues/2
    https://github.com/tapaswenipathak/GitGIFs/issues/3
    
   I would also request if someone else can help me complete the tickets as ticket numbers are huge and help would be appreciated. Else my aim is finish all till 9th.

**Comment by tapaswenipathak** [comment]
@sakshivij Can you tell me the number of GIFs in all tickets?

**Comment by prondubuisi** [comment]
**Completed tickets**

https://github.com/tapaswenipathak/TheLesserNumber/issues/29
https://github.com/tapaswenipathak/TheLesserNumber/issues/28
https://github.com/tapaswenipathak/TheLesserNumber/issues/27
https://github.com/tapaswenipathak/TheLesserNumber/issues/26
https://github.com/tapaswenipathak/TheLesserNumber/issues/24
https://github.com/tapaswenipathak/TheLesserNumber/issues/23
https://github.com/tapaswenipathak/TheLesserNumber/issues/22
https://github.com/tapaswenipathak/TheLesserNumber/issues/21
https://github.com/tapaswenipathak/TheLesserNumber/issues/20
https://github.com/tapaswenipathak/TheLesserNumber/issues/19
https://github.com/tapaswenipathak/TheLesserNumber/issues/17
https://github.com/tapaswenipathak/TheLesserNumber/issues/16
https://github.com/tapaswenipathak/TheLesserNumber/issues/15

**Planned tickets**

https://github.com/tapaswenipathak/TheLesserNumber/issues/16
https://github.com/tapaswenipathak/TheLesserNumber/issues/25

**Functionality tickets I should be reviewing**

Will be coming up with a document to guide you on this

**How many days of lag**

4 days

**What should be finished in next few day**

Gathering data for disability and child widow
**for question you need help on please write properly.**

No Questions

**Comment by sakshivij** [comment]
That needs to be completed or has been completed?

**Comment by tapaswenipathak** [comment]
On Thu, Jun 6, 2019 at 2:05 PM SAKSHI VIJ <notifications@github.com> wrote:
>
> That should be completed or has been completed?

Total tickets.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by sakshivij** [comment]
246.

**Comment by mamtashukla** [comment]
- Completed tickets
     https://github.com/alice-sieve/Linux-Kernel/issues/6 
     https://github.com/alice-sieve/Linux-Kernel/issues/7
     https://github.com/alice-sieve/Linux-Kernel/issues/8 
     https://github.com/alice-sieve/Linux-Kernel/issues/50
     Created html description for all core Kernel APIs

    - Planned tickets
      By EOD -
      https://github.com/alice-sieve/Linux-Kernel/issues/55
      Coming days -
      Remaining issues - https://github.com/alice-sieve/Linux-Kernel/issues

    - How many days of lag  -8 days

    - What should be finished in next few day
       Remaining issues for Linux Kernel APIs -https://github.com/alice-sieve/Linux-Kernel/issues
       and starting with assigned issues related to Uniform Service Testing for Linux Kernel
  
    - What help I need ?
      Which tickets I should proceed ahead? Should I install different kernel versions and check for   occurrences?

**Comment by sujay0399** [comment]
# Timeline

Total number of days - 21

Projects  - [YourCFP](https://github.com/tapaswenipathak/YourCFP),[OSDSResearchTillNow](https://github.com/tapaswenipathak/OSDSResearchTillNow),[JHPEC'19]( https://github.com/tapaswenipathak/IHeartGenomics)

Title | Dates | Tickets | Status 
--- | --- | --- | ---
Base CFP Django App<br> | May 19 | 1 | Completed
User Profiles<br> | May 20 | [2](https://github.com/tapaswenipathak/CFP/issues/11) | Completed
Create Form<br> | May 21  | [3](https://github.com/tapaswenipathak/CFP/issues/13) | Completed
Organisers can search for speaker<br> | May 22 | [4](https://github.com/tapaswenipathak/CFP/issues/15) | Completed
Save form as draft + send email reminder when deadline nears<br> | May 23 | [5](https://github.com/tapaswenipathak/CFP/issues/17) | Completed
Enabling accessibility<br> | May 24 | [6](https://github.com/tapaswenipathak/CFP/issues/20) | Pending
Save submitter's sessions and let them bulk submit them<br> | May 25 | [7](https://github.com/tapaswenipathak/CFP/issues/21) | Pending
Have travel info from organizers, and let them have it in their calendar.<br> | May 26 | [8](https://github.com/tapaswenipathak/CFP/issues/23) | Pending  
Organisers - Names, links, companies, automatically invisible until I tap on let me see. <br> | May 27 | [9](https://github.com/tapaswenipathak/CFP/issues/24) | Pending
Feedback on the submission being mandatory<br> | May 28 | [10](https://github.com/tapaswenipathak/CFP/issues/25) | Completed
Open leaderboard<br> | May 29 | [11](https://github.com/tapaswenipathak/CFP/issues/26) | Pending
Work on the production ready requirements<br> | May 30 | [12](https://github.com/tapaswenipathak/CFP/issues/27) | Pending
Production Ready Requirements<br> | May 31 | [13](https://github.com/tapaswenipathak/CFP/issues/28) | Pending
Genomics visualisation affecting disease<br> | June 1 | [1](https://github.com/tapaswenipathak/JHEPC-19/issues/6) | Pending
Django app creation country wise<br> | June 2 | [2](https://github.com/tapaswenipathak/JHEPC-19/issues/8) | Pending
Django app creation country wise<br> | June 3 | [2](https://github.com/tapaswenipathak/JHEPC-19/issues/8) | Pending
Django app creation country wise<br> | June 4 | [2](https://github.com/tapaswenipathak/JHEPC-19/issues/8) | Pending
Django app creation country wise<br> | June 5 | [2](https://github.com/tapaswenipathak/JHEPC-19/issues/8) | Pending
Website for Research papers<br> | June 6 | [3](https://github.com/tapaswenipathak/JHEPC-19/issues/12) | Pending
Implement Search<br> | June 7 | [4](https://github.com/tapaswenipathak/JHEPC-19/issues/13) | Pending
As the material is huge work on making search faster<br> | June 8 | [5](https://github.com/tapaswenipathak/JHEPC-19/issues/14) | Pending
Website for Research papers in OSDSResearch site<br> | June 9 | [1](https://github.com/tapaswenipathak/OSDSResearchTillNow/issues/2) | Pending
Implement Search<br> | June 10 | [2](https://github.com/tapaswenipathak/OSDSResearchTillNow/issues/3) | Pending
As the material is huge work on making search faster<br> | June 11 | [3](https://github.com/tapaswenipathak/OSDSResearchTillNow/issues/4) | Pending

Planned Tickets:
- https://github.com/tapaswenipathak/JHEPC-19/issues/6
- https://github.com/tapaswenipathak/JHEPC-19/issues/8
- https://github.com/tapaswenipathak/JHEPC-19/issues/12
- https://github.com/tapaswenipathak/JHEPC-19/issues/13
- https://github.com/tapaswenipathak/JHEPC-19/issues/14

- How many days of lag  -8 days

What should be finished in next few day
- https://github.com/tapaswenipathak/JHEPC-19/issues/6
- https://github.com/tapaswenipathak/JHEPC-19/issues/8
- https://github.com/tapaswenipathak/JHEPC-19/issues/12
- https://github.com/tapaswenipathak/JHEPC-19/issues/13
- https://github.com/tapaswenipathak/JHEPC-19/issues/14

What help I need ?
- I need a call for this.
- The task is publishing a website for research papers.I need to know what kind of research papers.
- What genomics data should be present on the site.

**Comment by tapaswenipathak** [comment]
Please submit whatever is in task list asap.

**Comment by tapaswenipathak** [comment]
Folks let's make sure all work is completed within few days.

**Comment by tapaswenipathak** [comment]
Can this ticket be closed?
