### ISSUE TITLE
This should be fun! 

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#34]
folks, all of you are putting up work in different projects, whenever you feel like chatting, feel free pinging me on tickets, Slack channel or mailing me. 

Mostly you are assigned the work per your interest, lemme know any questions you have.

In a day

- Send DocuSign doc - @tapaswenipathak 
- Sign and send - intern
- Ticket creation - @tapaswenipathak 
- Ack - intern
- Paper doc completion - intern

cc @Aashi15bansal @amulyaarunb @anantmoudgalya @anuragsarkar @AymanShafi @bhaskar07 @code-monk08 @horaanchal @mamtashukla @sakshivij @sujaykumarreddy @vermakhushboo

**Comment by code-monk08** [comment]
Ack, btw what's Paper Doc?

**Comment by bymayanksingh** [comment]
Ack.

**Comment by anantmoudgalya** [comment]
I haven't been assigned anything yet, should I be waiting?
