### ISSUE TITLE
Tickets on me

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#35]
folks, I have assigned few tickets on me w/ you, those are the tickets where I will be reviewing the work required for paper, everything else straight away merge town, put a gif or screenshot of output, write @tapaswenipathak when you merge.

cc @Aashi15bansal @amulyaarunb @anantmoudgalya @anuragsarkar @AymanShafi @bhaskar07 @code-monk08 @horaanchal @mamtashukla @sakshivij @sujaykumarreddy @vermakhushboo

**Comment by bymayanksingh** [comment]
Ack
