### ISSUE TITLE
Submitting the work

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#37]
folks, you all have been added as collaborator for the repositories you will adding the work, you should

- push a branch (don't fork)
- add work
- add gifs/screenshots
- pr
- merge
- close the ticket (write @tapaswenipathak when you close a ticket)

I will only review where I have added myself. Please add work per day, divide the work where there are multiple people assigned a ticket. Lemme know any questions you have, just drop them in Slack channel write @tapaswenipathak. 

cc @Aashi15bansal @amulyaarunb @anikamurarka  @anantmoudgalya @anuragsarkar @AymanShafi @bhaskar07 @code-monk08 @csamarth @horaanchal @KevinChittilapilly @kumar-hardik @mamtashukla @sakshivij @sujaykumarreddy @ucalyptus @vermakhushboo

**Comment by bymayanksingh** [comment]
Ack
