### ISSUE TITLE
Work timelines

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#38]
Hey folks, can we all post work timelines 

- Tickets planned till today
- Tickets completed
- Tickets remaining
- Any issues you are facing where I can pitch in

Please let me know any questions you have! I am there in Slack, mail and on GitHub. 

@Aashi15bansal @amulyaarunb @anikamurarka @anantmoudgalya @anuragsarkar @AymanShafi @bhaskar07 @code-monk08 @csamarth @horaanchal @KevinChittilapilly @kumar-hardik @mamtashukla @sakshivij @sujaykumarreddy @ucalyptus @vermakhushboo

**Comment by tapaswenipathak** [comment]
- [x] Write tickets
- [x] Slack pings, dropbox calendars
- [x] Send docusign paper work
- [x] Form GitHub group 
- [x] Reschedule cancelled meetings
- [x] Papers writings

I will finish till end of today. Feel free reminding me if there is anything else I should have completed till today.

**Comment by tapaswenipathak** [comment]
Please ack tickets posted. Write `ack` and you are done.

**Comment by Aashi15bansal** [comment]
ack

**Comment by bymayanksingh** [comment]
ack

**Comment by csamarth** [comment]
ack

**Comment by KevinChittilapilly** [comment]
ack

**Comment by ucalyptus** [comment]
ack
