### ISSUE TITLE
Please keep on closing the tickets after you are done

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#41]
There are many tickets on my name that I have opened, please keep on closing the tasks as and when you are done pring the work. @Aashi15bansal @amulyaarunb @anikamurarka @anantmoudgalya @anuragsarkar @AymanShafi @bhaskar07 @code-monk08 @csamarth @horaanchal @KevinChittilapilly @kumar-hardik @mamtashukla @sakshivij @sujaykumarreddy @ucalyptus @vermakhushboo

**Comment by tapaswenipathak** [comment]
Please text or DM in Slack channel for anything.

**Comment by sujay0399** [comment]
ack

**Comment by tapaswenipathak** [comment]
Please only request access for tickets you are assigned.

**Comment by ucalyptus** [comment]
ack

**Comment by bymayanksingh** [comment]
ack
