### ISSUE TITLE
Folks, please ack

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#43]
Everything should be documented, I want a ack from all of you. Without docs I just can't keep track of all the work.

<img width="726" alt="Screen Shot 2019-07-06 at 9 17 55 PM" src="https://user-images.githubusercontent.com/4143778/60758434-33d74400-a034-11e9-9ca0-1419b1b4b45d.png">

**Comment by sujay0399** [comment]
Ack

**Comment by charusinha** [comment]
Ack

**Comment by ghost** [comment]
Ack

**Comment by kumar-hardik** [comment]
Ack

**Comment by Aashi15bansal** [comment]
ack

**Comment by nightwarriorftw** [comment]
ack

**Comment by dhirensr** [comment]
Ack

**Comment by ucalyptus** [comment]
Ack

**Comment by bymayanksingh** [comment]
ack

**Comment by NiharikaMessi** [comment]
Ack

**Comment by KevinChittilapilly** [comment]
ack

**Comment by shah-aman** [comment]
ack

**Comment by shah-aman** [comment]
ack

**Comment by tapaswenipathak** [comment]
Folks, write your cell numbers in the doc.

**Comment by tapaswenipathak** [comment]
Just a reminder, I can't afford lack of response or missing deadlines. Slack check is must daily.

**Comment by prateekmaj21** [comment]
ack

**Comment by mayankchauhan971** [comment]
Ack

**Comment by amit-sharma-9** [comment]
Ack
