### ISSUE TITLE
Complete task list

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#5]
- Add calendars
- Add timelines
- Add daily logs till now

@armorer96  @anuragsarkar @prondubuisi @sakshivij @sujaykumarreddy.

Please let me know if you need any help.

**Comment by prondubuisi** [comment]
Hello @tapaswenipathak  are to add the calendar to the lesser number Repo?

**Comment by tapaswenipathak** [comment]
On Wed, May 22, 2019 at 9:07 PM Onyemenam Ndubuisi
<notifications@github.com> wrote:
>
> Hello @tapaswenipathak should I add the calendar to the lesser number Repo?

Please add the calendar and timeline in
https://github.com/tapaswenipathak/Timelines.


>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
Tapasweni
