### ISSUE TITLE
Interns Slack channel

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Interns-qna#7]
folks, I have sent a Slack channel invite, you will join https://opensourcehelp.slack.com/ after you accept the invite. I have created a channel for communication in the channel. 

cc @anuragsarkar @Armorer96  @prondubuisi @sakshivij @sujaykumarreddy.

**Comment by tapaswenipathak** [comment]
@anuragsarkar @sujaykumarreddy I don't see you in the channel.

**Comment by sujaykumarreddy** [comment]
@tapaswenipathak 
I joined the channel a while ago.What is the name of the thread to reach out?

**Comment by tapaswenipathak** [comment]
On Tue, 28 May 2019, 08:52 sujay Reddy <notifications@github.com wrote:

> @tapaswenipathak <https://github.com/tapaswenipathak>
> I joined the channel.What is the name of the thread I should join?
>

I added you in the interns Slack channel.

**Comment by anuragsarkar** [comment]
I have joined it please add me too.

**Comment by tapaswenipathak** [comment]
On Tue, May 28, 2019 at 5:11 PM Anurag Sarkar <notifications@github.com> wrote:
>
> I have joined it please add me.

I have added.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
